optimise entrypoint

diff --git a/client/scripts/sw-docker-entrypoint b/client/scripts/sw-docker-entrypoint
--- a/client/scripts/sw-docker-entrypoint
+++ b/client/scripts/sw-docker-entrypoint
@@ -9,6 +9,10 @@ PIP_CACHE_DIR=${SW_PIP_CACHE_DIR:=/root/.cache/pip}
 _MANIFEST_RUNTIME=$(cat ${WORKDIR}/_manifest.yaml| grep "python:" | awk '{print $2}' | awk -F '.' '{print $1"."$2}') || true
 _MODEL_RUNTIME=$(cat ${WORKDIR}/model.yaml | grep 'runtime' | awk '{print $2}') || true
 VERBOSE="-vvvv"
+EVAL_VERSION=${SW_EVAL_VERSION}
+DATASETS=${SW_DATASETS}
+STEP=${SW_TASK_STEP}
+TASK_INDEX=${SW_TASK_INDEX:=0}
 
 _update_python_alter() {
     echo "--> set python/python3 to $1 ..."
@@ -60,10 +64,10 @@ pre_check() {
         exit 1
     fi
 
-    if [ ! -f "${SW_TASK_INPUT_CONFIG}" ]; then
-        echo "${SW_TASK_INPUT_CONFIG} not found, please set env and volume file into container"
-        exit 1
-    fi
+    # if [ ! -f "${SW_TASK_INPUT_CONFIG}" ]; then
+    #     echo "${SW_TASK_INPUT_CONFIG} not found, please set env and volume file into container"
+    #     exit 1
+    # fi
 }
 
 set_python() {
@@ -80,7 +84,7 @@ set_python() {
         _update_python_alter "python3.8"
     fi
 }
-
+# TODO:restore when processing evaluation(eval run use param: 'runtime URI', and it can be uri or dir path )
 restore_activate_runtime() {
     echo '--> restore python env ...'
     export PYTHONWARNINGS="ignore:Unverified HTTPS request"
@@ -91,14 +95,14 @@ restore_activate_runtime() {
     eval "$(./activate.sw)"
 }
 
-run_ppl() {
-    echo "--> start to run swmp ppl, use $(which swcli) cli..."
-    swcli ${VERBOSE} model ppl ${WORKDIR}/src
+run_all() {
+    echo "--> start to run swmp all, use $(which swcli) cli..."
+    swcli ${VERBOSE} eval run --type=all --model=${WORKDIR}/src --dataset=${DATASETS} --version=${EVAL_VERSION}
 }
 
-run_cmp() {
-    echo "--> start to run swmp cmp, use $(which swcli) cli..."
-    swcli ${VERBOSE} model cmp ${WORKDIR}/src
+run_single() {
+    echo "--> start to run swmp single, use $(which swcli) cli..."
+    swcli ${VERBOSE} eval run --type=single --model=${WORKDIR}/src --dataset=${DATASETS} --step=${STEP} --task-index=${TASK_INDEX} --version=${EVAL_VERSION}
 }
 
 welcome() {
@@ -119,10 +123,10 @@ main() {
     set_pip_cache
     restore_activate_runtime
 
-    if [ "$1" = "cmp" ]; then
-        run_cmp
+    if [ "$1" = "all" ]; then
+        run_all
     else
-        run_ppl
+        run_single
     fi
 }
 
